Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,12 +30,12 @@ jobs:
 
     - name: Run FastAPI server in background
       run: |
-        uvicorn app:app --host 0.0.0.0 --port 8002 &
+        uvicorn app:app --host 0.0.0.0 --port 8000 &
         sleep 10
 
     - name: Test FastAPI home endpoint
       run: |
-        curl --http1.1 http://localhost:8002/ || { echo "Home endpoint failed"; exit 1; }
+        curl --http1.1 http://localhost:8000/ || { echo "Home endpoint failed"; exit 1; }
 
     - name: Test FastAPI predict endpoint
       run: |
@@ -54,16 +54,16 @@ jobs:
 
     - name: Run Docker container
       run: |
-        docker run -d -p 8002:8002 --name shipment-container shipment-live-prec
+        docker run -d -p 8000:8000 --name shipment-container shipment-live-prec
         sleep 10
 
     - name: Test Dockerized FastAPI home endpoint
       run: |
-        curl --http1.1 http://localhost:8002/ || { echo "Docker home endpoint failed"; exit 1; }
+        curl --http1.1 http://localhost:8000/ || { echo "Docker home endpoint failed"; exit 1; }
 
     - name: Test Dockerized FastAPI predict endpoint
       run: |
-        curl --http1.1 -X POST http://localhost:8002/predict -H "Content-Type: application/json" -d '{"Warehouse_block":"A","Mode_of_Shipment":"Flight","Customer_care_calls":2,"Customer_rating":3,"Cost_of_the_Product":150.0,"Prior_purchases":3,"Product_importance":"low","Gender":"F","Discount_offered":10.0,"Weight_in_gms":2000.0}' || { echo "Predict endpoint failed"; exit 1; }
+        curl --http1.1 -X POST http://localhost:8000/predict -H "Content-Type: application/json" -d '{"Warehouse_block":"A","Mode_of_Shipment":"Flight","Customer_care_calls":2,"Customer_rating":3,"Cost_of_the_Product":150.0,"Prior_purchases":3,"Product_importance":"low","Gender":"F","Discount_offered":10.0,"Weight_in_gms":2000.0}' || { echo "Predict endpoint failed"; exit 1; }
 
     - name: Stop Docker container
       run: |
