Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -39,7 +39,7 @@ jobs:
 
     - name: Test FastAPI predict endpoint
       run: |
-        curl --http1.1 -X POST http://localhost:8002/predict -H "Content-Type: application/json" -d '{"Warehouse_block":"A","Mode_of_Shipment":"Flight","Customer_care_calls":2,"Customer_rating":3,"Cost_of_the_Product":150.0,"Prior_purchases":3,"Product_importance":"low","Gender":"F","Discount_offered":10.0,"Weight_in_gms":2000.0}' || { echo "Predict endpoint failed"; exit 1; }
+        curl --http1.1 -X POST http://localhost:8000/predict -H "Content-Type: application/json" -d '{"Warehouse_block":"A","Mode_of_Shipment":"Flight","Customer_care_calls":2,"Customer_rating":3,"Cost_of_the_Product":150.0,"Prior_purchases":3,"Product_importance":"low","Gender":"F","Discount_offered":10.0,"Weight_in_gms":2000.0}' || { echo "Predict endpoint failed"; exit 1; }
 
     - name: Stop FastAPI server
       run: |
